stages:                 # Les étapes associées au projet.
  - lint                # Pour la vérification statique du code 
  - build               # fabrication de l'application
  - test                # Test de l'application
  - deploy              # Deploiement


lint-js-backend:      #Vérificaition de la qualité du code js du backend
  stage: lint
  tags:
    - docker
  image: node
  script: 
    - cd root/Backend/ 
    - npm init @eslint/config 
    - ./scripts/lintjs.sh  #Script qui éffectue les vérifications sur le backend
  artifacts:
    paths:  #Le rapport est diponible à la fin
      - root/Backend/lintjs-report.out
  only:
    # changes:
    #   - "*.js"


TestBackend:
  stage: test
  tags:
    - docker  # Comme on utilise une image pour isoler on doit utiliser un runner docker 
  image: node 
  script:
    - cd root/Backend
    - npm run setup # Installe ce qui est décrit dans package.json
    - npm run test # Lance les tests jest
  # only:
  #     changes:
  #       - "*.js"

